// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohwtyzwiwgigjtkligac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9od3R5endpd2dpZ2p0a2xpZ2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDYzODAsImV4cCI6MjA3MzMyMjM4MH0.21A5dPLMpbUQP4zPcELzwWqs-65c4bOc0TM3IWkclsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});